/**
 * Unified signal model (PART 6) and data-class labelling (PART 28).
 *
 * Every physiological record in the platform — demo, imported or manually
 * entered — is normalised into the same shape so that quality assessment,
 * processing and fusion can run against one contract instead of three.
 *
 * Two deliberate design choices:
 *
 *  1. `values` are NOT stored on the record. A 250 Hz ECG minute is 15,000
 *     floats; keeping arrays like that in React state or localStorage freezes
 *     the interface. Instead a record declares how its samples can be
 *     obtained (`valuesStorage`) and `resolveSignalValues()` materialises only
 *     the window that is asked for. This is the
 *     import → validate → process → features → metadata → window architecture
 *     the specification requires for large datasets.
 *
 *  2. Provenance is never optional. A record without a source is stored with
 *     `source: 'Source not stated'` rather than being given a plausible one,
 *     and a record whose data class was not declared is labelled
 *     `unspecified` rather than defaulting to "real user data".
 */

import { getSignalType, signalTypeLabel, signalCategoryLabel, KIND_LABEL } from '../data/signalTaxonomy.js';
import { generateSignalValues, DEMO_SIGNAL_SOURCE, DEMO_DATA_CLASS } from '../data/demoBioSignals.js';

export const SIGNAL_MODEL_VERSION = '1.0.0';

/** PART 28 — the three data classes must never be mixed silently. */
export const DATA_CLASSES = [
  {
    id: 'real-user',
    label: 'Real user data',
    note: 'Entered or imported by the user of this device/browser',
    requiresSource: true,
  },
  {
    id: 'research-dataset',
    label: 'Research dataset',
    note: 'Published or supplied research data with a citable origin',
    requiresSource: true,
  },
  {
    id: 'synthetic-demo',
    label: 'Synthetic / Demo Data',
    note: 'Generated by this application. No real subject, no clinical meaning',
    requiresSource: false,
  },
  {
    id: 'unspecified',
    label: 'Data class not stated',
    note: 'The importer did not declare whether this record is real, research or synthetic',
    requiresSource: true,
  },
];

const DATA_CLASS_IDS = new Set(DATA_CLASSES.map((c) => c.id));

export function dataClassLabel(id) {
  return DATA_CLASSES.find((c) => c.id === id)?.label ?? 'Data class not stated';
}

export function dataClassNote(id) {
  return DATA_CLASSES.find((c) => c.id === id)?.note ?? '';
}

export function isSynthetic(id) {
  return id === DEMO_DATA_CLASS || id === 'synthetic-demo';
}

/**
 * PART 6 — the source must always be present. These are the recognised kinds;
 * the free-text `source` field on a record holds the specific description.
 */
export const SOURCE_KINDS = [
  { id: 'wearable', label: 'Wearable' },
  { id: 'ecg-device', label: 'ECG device' },
  { id: 'eeg-device', label: 'EEG device' },
  { id: 'cgm-device', label: 'Continuous glucose monitor' },
  { id: 'research-dataset', label: 'Research dataset' },
  { id: 'uploaded-file', label: 'Uploaded file' },
  { id: 'manual-entry', label: 'Manual entry' },
  { id: 'demo-generator', label: 'Synthetic demo generator' },
  { id: 'unknown', label: 'Source not stated' },
];

export function sourceKindLabel(id) {
  return SOURCE_KINDS.find((s) => s.id === id)?.label ?? 'Source not stated';
}

/** How a record's samples can be obtained. */
export const VALUES_STORAGE = {
  'generated-on-demand': 'Samples are regenerated from a declared seed for the requested window only',
  inline: 'Samples are stored on the record',
  'file-reference': 'Samples live in an imported file that was not loaded into memory',
  'not-stored': 'No sample values are available for this record',
  metadata: 'Metadata only — this record describes measurements, not samples',
};

let seq = 0;

/** Short unique id. Not cryptographically meaningful — never used as a subject key. */
export function makeSignalId(prefix = 'sig') {
  seq += 1;
  return `${prefix}-${Date.now().toString(36)}-${seq.toString(36)}`;
}

/**
 * Normalise anything shaped like a signal into the unified record.
 *
 * @param {object} input  partial record (importer output, manual form, demo template)
 * @param {object} ctx    { provenance, values, valuesStorage }
 */
export function normalizeSignal(input = {}, ctx = {}) {
  const type = getSignalType(input.type);
  const dataClass = DATA_CLASS_IDS.has(input.dataClass) ? input.dataClass : 'unspecified';

  const inline = Array.isArray(input.values) && input.values.length > 0 ? input.values : ctx.values;
  let valuesStorage = input.valuesStorage ?? ctx.valuesStorage;
  if (!valuesStorage) {
    if (Array.isArray(inline) && inline.length) valuesStorage = 'inline';
    else if (input.source === DEMO_SIGNAL_SOURCE) valuesStorage = 'generated-on-demand';
    else if (input.fileId || input.originalFilename) valuesStorage = 'file-reference';
    else valuesStorage = 'not-stored';
  }

  const source = String(input.source ?? '').trim() || 'Source not stated';
  const sourceKind =
    input.sourceKind ??
    (source === DEMO_SIGNAL_SOURCE
      ? 'demo-generator'
      : source === 'Manual entry'
        ? 'manual-entry'
        : source.startsWith('Uploaded')
          ? 'uploaded-file'
          : 'unknown');

  const record = {
    id: input.id ?? makeSignalId(),
    subjectId: String(input.subjectId ?? '').trim() || null,
    type: type ? type.id : String(input.type ?? 'unknown'),
    typeLabel: type ? type.label : String(input.type ?? 'Unknown signal type'),
    category: type ? type.category : String(input.category ?? 'uncategorized'),
    categoryLabel: type ? signalCategoryLabel(type.id) : 'Uncategorized',
    kind: type ? type.kind : String(input.kind ?? 'derived'),
    kindLabel: type ? KIND_LABEL[type.kind] : 'Unclassified',

    // The profile decides which algorithms are legitimate. If the type is not in
    // the catalogue there is no profile to inherit, and inventing one would let
    // the processing engine run algorithms nobody declared appropriate. It stays
    // null, which runProcessing reports as "not applicable" rather than as a
    // computed result.
    profile: type ? type.profile : (input.profile ?? null),
    typeKnown: Boolean(type),

    // PART 6 — source information is mandatory; it is never fabricated.
    source,
    sourceKind,
    sourceKindLabel: sourceKindLabel(sourceKind),
    device: String(input.device ?? '').trim() || 'Device not stated',

    timestamp: input.timestamp ?? null,
    durationSec: Number.isFinite(input.durationSec) ? input.durationSec : null,
    samplingRate: Number.isFinite(input.samplingRate) && input.samplingRate > 0 ? input.samplingRate : null,
    unit: input.unit ?? (type ? type.unit : null),
    channel: input.channel ?? (type ? type.channel : null),

    dataClass,
    dataClassLabel: dataClassLabel(dataClass),

    valuesStorage,
    valuesStorageNote: VALUES_STORAGE[valuesStorage] ?? '',
    discreteCount: Number.isFinite(input.discreteCount) ? input.discreteCount : null,
    defects: input.defects ?? {},

    // PART 7 — filled in by the quality engine; null means "not assessed yet".
    quality: input.quality ?? null,

    // PART 27 — provenance block, created by src/lib/provenance.js on import.
    provenance: input.provenance ?? ctx.provenance ?? null,

    metadata: {
      modelVersion: SIGNAL_MODEL_VERSION,
      clinicalMeaning: isSynthetic(dataClass)
        ? 'none — simulated waveform'
        : 'Research measurement. Not a diagnosis and not a clinical reading.',
      ...(input.metadata ?? {}),
    },
  };

  // Keep the actual array off the persisted record when it is large.
  if (valuesStorage === 'inline' && Array.isArray(inline)) {
    record._inlineValues = inline;
    if (input.times) record._inlineTimes = input.times;
  }

  return record;
}

/** True for records whose samples form a continuous time series. */
export function isContinuousSignal(record) {
  return record.kind === 'raw' || (record.kind === 'derived' && Boolean(record.samplingRate));
}

export function isCategoricalSignal(record) {
  return record.kind === 'categorical';
}

export function isDiscreteSignal(record) {
  return record.kind === 'discrete';
}

export function isNumericSignal(record) {
  return !isCategoricalSignal(record);
}

/**
 * Materialise a window of samples for a record.
 *
 * Returns `{ t0, dt, n, values, labels, times, error }`. When samples cannot be
 * produced, `error` explains why — the caller must show that message instead of
 * rendering an empty chart as though the signal were flat.
 */
export function resolveSignalValues(record, opts = {}) {
  if (!record) {
    return emptyWindow('No signal record was supplied.');
  }
  if (record._inlineValues?.length) {
    return sliceInline(record, opts);
  }
  if (record.valuesStorage === 'generated-on-demand' || record.source === DEMO_SIGNAL_SOURCE) {
    const win = generateSignalValues(record, opts);
    if (win.error) return { ...emptyWindow(win.error), t0: win.t0 };
    return win;
  }
  if (record.valuesStorage === 'file-reference') {
    return emptyWindow(
      'Samples for this record are held in the imported file and were not loaded into memory. Re-import with sample extraction enabled to analyse the waveform.',
    );
  }
  return emptyWindow('No sample values are stored for this record.');
}

function emptyWindow(error) {
  return { t0: 0, dt: null, n: 0, values: [], labels: null, times: null, error };
}

function sliceInline(record, opts) {
  const all = record._inlineValues;
  const times = record._inlineTimes ?? null;
  const labels = record._inlineLabels ?? null;
  const startSec = Math.max(0, opts.startSec ?? 0);
  const dt = record.samplingRate ? 1 / record.samplingRate : times ? null : 1;

  let from = 0;
  let to = all.length;
  if (times) {
    const t0 = times[0] ?? 0;
    from = times.findIndex((t) => t - t0 >= startSec);
    if (from < 0) from = 0;
    const lengthSec = opts.lengthSec ?? null;
    if (lengthSec) {
      to = times.findIndex((t) => t - t0 >= startSec + lengthSec);
      if (to < 0) to = all.length;
    }
  } else if (dt) {
    from = Math.min(all.length - 1, Math.round(startSec / dt));
    if (opts.lengthSec) to = Math.min(all.length, from + Math.round(opts.lengthSec / dt));
  }

  const values = all.slice(from, to);
  const maxPoints = opts.maxPoints ?? 2000;
  const step = values.length > maxPoints ? Math.ceil(values.length / maxPoints) : 1;
  const out = [];
  const outT = [];
  for (let i = 0; i < values.length; i += step) {
    out.push(values[i]);
    if (times) outT.push(times[from + i]);
  }
  return {
    t0: times ? times[from] ?? 0 : startSec,
    dt: dt ? dt * step : null,
    n: out.length,
    values: out,
    labels: labels ? labels.slice(from, to) : null,
    times: times ? outT : null,
    error: null,
  };
}

/** Absolute time array (seconds from the recording start) for a window. */
export function windowTimes(win) {
  if (win.times) return win.times;
  const out = new Array(win.n);
  for (let i = 0; i < win.n; i += 1) out[i] = (win.t0 ?? 0) + i * (win.dt ?? 0);
  return out;
}

/** ISO timestamp for an offset in seconds from a record's start. */
export function timestampAtOffset(record, offsetSec) {
  const base = record?.timestamp ? Date.parse(record.timestamp) : NaN;
  if (!Number.isFinite(base)) return null;
  return new Date(base + Math.round(offsetSec * 1000)).toISOString();
}

/** Plain-language description used in evidence chains and reports. */
export function describeSignal(record) {
  if (!record) return 'No signal record.';
  const parts = [record.typeLabel ?? signalTypeLabel(record.type)];
  if (record.subjectId) parts.push(`subject ${record.subjectId}`);
  parts.push(record.kindLabel);
  if (record.samplingRate) parts.push(`${formatRate(record.samplingRate)} sampling`);
  if (record.durationSec) parts.push(`${formatDuration(record.durationSec)} recording`);
  parts.push(`source: ${record.source}`);
  parts.push(record.dataClassLabel);
  return parts.join(' · ');
}

export function formatRate(fs) {
  if (!fs) return 'rate not stated';
  if (fs < 1) return `1 sample / ${formatDuration(1 / fs)}`;
  return `${fs} Hz`;
}

export function formatDuration(sec) {
  if (!Number.isFinite(sec)) return 'duration not stated';
  if (sec < 60) return `${Math.round(sec * 10) / 10} s`;
  if (sec < 3600) return `${Math.round(sec / 60)} min`;
  if (sec < 86400) return `${Math.round((sec / 3600) * 10) / 10} h`;
  return `${Math.round(sec / 86400)} d`;
}

/** Short label for badges and tables — always includes the data class. */
export function signalTableLabel(record) {
  return `${record.typeLabel ?? record.type} · ${record.subjectId ?? 'no subject'} · ${record.dataClassLabel}`;
}

export { signalTypeLabel, signalCategoryLabel, KIND_LABEL, DEMO_SIGNAL_SOURCE };
