import { useState } from 'react';
import Icon from '../components/icons.jsx';
import { Panel, Badge, Meter, ProtoTag, StatCard } from '../components/ui/index.js';
import LineChart from '../components/charts/LineChart.jsx';
import { DEVICE_PROFILE, WEEKLY_DEVICE } from '../data/syntheticData.js';
import { driftReport, calibrationReport, generateDeviceReading } from '../lib/engine.js';
import { logEvent } from '../lib/audit.js';

/**
 * Low-cost Multi-Biomarker Device interface (modules #1, #8) with sensor
 * drift detection (#22) and calibration monitoring (#23). The device is
 * entirely simulated — the "sync" button generates a synthetic reading
 * and records it in the local audit trail.
 */
export default function DeviceInterface() {
  const [readings, setReadings] = useState(() =>
    WEEKLY_DEVICE.slice(-3).map((p) => ({
      ts: p.label,
      glucose: p.glucose,
      hba1c: p.hba1c,
      bmi: p.bmi,
      triglycerides: p.triglycerides,
      quality: 90,
      simulated: false,
    })),
  );
  const [syncing, setSyncing] = useState(false);
  const [lastSync, setLastSync] = useState('1 h ago');

  const syncNow = () => {
    if (syncing) return;
    setSyncing(true);
    window.setTimeout(() => {
      const reading = generateDeviceReading();
      setReadings((prev) => [{ ...reading, simulated: true }, ...prev].slice(0, 8));
      setLastSync('just now');
      setSyncing(false);
      logEvent(
        'MEASUREMENT_RECEIVED',
        `Simulated sync received a device batch (glucose ${reading.glucose} mg/dL, quality ${reading.quality}/100).`,
        { source: 'SH-1 patch (simulated)', batch: reading },
      );
    }, 700);
  };

  const driftSeries = [
    {
      id: 'residual',
      label: 'Device − reference (glucose)',
      color: 'var(--warn)',
      points: driftReport.weekly.map((p) => ({ x: p.x, y: p.y })),
    },
    {
      id: 'zero',
      label: 'Perfect agreement',
      color: 'var(--ink-400)',
      dashed: true,
      points: driftReport.weekly.map((p) => ({ x: p.x, y: 0 })),
    },
  ];

  return (
    <>
      <div className="stat-grid">
        <StatCard
          label="Connection"
          value="Paired"
          note="BLE link · SH-1 patch (simulated) · firmware v0.4.2-proto"
          tone="good"
          icon={<Icon name="bluetooth" size={16} />}
        />
        <StatCard
          label="Battery"
          value="71"
          unit="%"
          note="≈ 9 days remaining at the current duty cycle"
          tone="good"
          icon={<Icon name="activity" size={16} />}
        />
        <StatCard
          label="Offline capability"
          value={DEVICE_PROFILE.offlineCapablePct}
          unit="%"
          note="Buffer currently 64% full · 30-day rolling storage"
          tone="info"
          icon={<Icon name="moon" size={16} />}
        />
        <StatCard
          label="Unit cost (BOM)"
          value={`$${DEVICE_PROFILE.bomCostUsd}`}
          note={`Target price $${DEVICE_PROFILE.targetPriceUsd} — low-resource design goal`}
          tone="neutral"
          icon={<Icon name="info" size={16} />}
        />
      </div>

      <div className="dashboard-row">
        <Panel
          title="Simulated device measurements"
          subtitle="Live sync from the SH-1 multi-biomarker patch — all values synthetic"
          aside={
            <button
              type="button"
              className={`action-button ${syncing ? 'busy' : ''}`}
              onClick={syncNow}
              disabled={syncing}
            >
              {syncing ? 'Syncing…' : 'Sync now'}
            </button>
          }
        >
          <div className="mini-table-wrap">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Received</th>
                  <th>Glucose (mg/dL)</th>
                  <th>HbA1c (%)</th>
                  <th>BMI</th>
                  <th>TG (mg/dL)</th>
                  <th>Batch quality</th>
                </tr>
              </thead>
              <tbody>
                {readings.map((r, idx) => (
                  <tr key={`${r.ts}-${idx}`}>
                    <td>
                      {r.ts}
                      {r.simulated && (
                        <span className="table-flag" title="Generated by this browser during the demo sync">
                          {' '}
                          new
                        </span>
                      )}
                    </td>
                    <td className="num">{r.glucose}</td>
                    <td className="num">{r.hba1c}</td>
                    <td className="num">{r.bmi}</td>
                    <td className="num">{r.triglycerides}</td>
                    <td>
                      <Badge tone={r.quality >= 90 ? 'good' : 'warn'}>{r.quality}/100</Badge>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <p className="muted-small" style={{ marginTop: 10 }}>
            Last sync {lastSync}. “Sync now” generates a fresh synthetic batch in this
            browser and appends a MEASUREMENT_RECEIVED event to the local audit trail —
            no data leaves this page.
          </p>
        </Panel>

        <Panel title="Onboard sensors" subtitle="Five sensing modalities on one patch">
          <ul className="sensor-list">
            {DEVICE_PROFILE.sensors.map((s) => (
              <li key={s}>
                <span className="sensor-dot" />
                {s}
              </li>
            ))}
          </ul>
          <div className="resource-meters">
            {DEVICE_PROFILE.resource.map((r) => (
              <div key={r.label} className="meter-stack-item">
                <Meter label={`${r.label} — ${r.detail}`} value={r.value} tone="info" suffix="%" />
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <Panel
        title="Sensor drift detection"
        subtitle="Weekly device glucose minus paired reference-lab draw"
        aside={<Badge tone={driftReport.status}>{driftReport.statusLabel}</Badge>}
      >
        <LineChart
          series={driftSeries}
          height={210}
          formatX={(w) => WEEKLY_DEVICE[Math.round(w)]?.label ?? ''}
          formatY={(v) => `${+v.toFixed(1)}`}
          yLabel="Residual (mg/dL)"
        />
        <p className="muted-small" style={{ marginTop: 10 }}>
          {driftReport.summary} Recent 4-week mean residual:{' '}
          <strong>{driftReport.recentMean > 0 ? '+' : ''}{driftReport.recentMean} mg/dL</strong>.
        </p>
      </Panel>

      <div className="dashboard-row">
        <Panel
          title="Calibration monitor"
          subtitle="Prototype policy — recalibrate every 8 weeks"
          aside={<Badge tone={calibrationReport.status}>{calibrationReport.statusLabel}</Badge>}
        >
          <ul className="plain-list">
            <li>
              <span>Last calibration</span>
              <strong>{calibrationReport.lastCalibration}</strong>
            </li>
            <li>
              <span>Cadence</span>
              <strong>{calibrationReport.cadence}</strong>
            </li>
            <li>
              <span>Next due</span>
              <strong>{calibrationReport.nextDue}</strong>
            </li>
          </ul>
          <p className="muted-small" style={{ marginTop: 10 }}>
            {calibrationReport.reason}
          </p>
        </Panel>

        <Panel
          title="Low-resource design envelope"
          subtitle="Prototype targets for low-cost, low-power deployment"
          aside={<ProtoTag compact />}
        >
          <ul className="plain-list">
            <li>
              <span>Average power</span>
              <strong>{DEVICE_PROFILE.avgPowerMw} mW (peak {DEVICE_PROFILE.peakPowerMw} mW)</strong>
            </li>
            <li>
              <span>Sync interval</span>
              <strong>{DEVICE_PROFILE.syncInterval}</strong>
            </li>
            <li>
              <span>Offline-first</span>
              <strong>100% of analytics run on-device</strong>
            </li>
            <li>
              <span>Bill of materials</span>
              <strong>${DEVICE_PROFILE.bomCostUsd} at prototype volume</strong>
            </li>
          </ul>
          <p className="muted-small" style={{ marginTop: 10 }}>
            Figures are design targets for the simulated hardware — not measured
            values from a physical device.
          </p>
        </Panel>
      </div>
    </>
  );
}
