import { Panel, Badge, ProtoTag } from '../components/ui/index.js';
import Icon from '../components/icons.jsx';
import { DISEASE_MODULES } from '../data/syntheticData.js';

const STATUS_TONE = { Active: 'good', Planned: 'info', Exploratory: 'proto' };

/**
 * Disease-Agnostic Architecture (module #9).
 * The registry of disease modules that plug into the shared biomarker
 * pipeline. Only the Type 2 Diabetes module is active — and it runs on
 * synthetic data as an unvalidated research demo.
 */
export default function DiseaseModules() {
  return (
    <>
      <Panel
        title="Disease module registry"
        subtitle="One shared biomarker pipeline, pluggable disease modules — the core architectural idea"
        aside={<ProtoTag compact />}
      >
        <p className="fact-note" style={{ marginBottom: 14 }}>
          The system is designed disease-agnostic: a module declares which biomarkers it
          needs and how it models trajectories, while device collection, baselining,
          deviation detection and explanation infrastructure stay shared. Adding a disease
          should mean adding a module — not rebuilding the platform.
        </p>

        <div className="info-grid">
          {DISEASE_MODULES.map((m) => (
            <article key={m.id} className="info-card">
              <div className="info-card-head">
                <span className="notice-icon" aria-hidden="true">
                  <Icon name={m.icon} size={18} />
                </span>
                <strong>{m.name}</strong>
                <Badge tone={STATUS_TONE[m.status] ?? 'neutral'}>{m.status}</Badge>
              </div>
              <p>{m.description}</p>
              {m.features && (
                <div className="chip-row">
                  {m.features.map((f) => (
                    <span key={f} className="chip">{f}</span>
                  ))}
                </div>
              )}
              <div className="info-card-meta">
                {m.version && <span>Model — {m.version}</span>}
                {m.coverage && <span>Data — {m.coverage}</span>}
                {m.eta && <span>Roadmap — {m.eta}</span>}
              </div>
            </article>
          ))}
        </div>
      </Panel>

      <Panel
        title="What “active” means here"
        subtitle="Scope statement for the T2D module"
        aside={<Badge tone="warn">Not a medical device</Badge>}
      >
        <ul className="plain-list">
          <li><span>Input data</span><strong>Synthetic monthly panel generated by a seeded PRNG</strong></li>
          <li><span>Scorer</span><strong>Transparent weighted-logistic demonstration (demo-ensemble-v0.3)</strong></li>
          <li><span>Clinical validation</span><strong>None — outputs are research estimates only</strong></li>
          <li><span>Planned modules</span><strong>Hypertension &amp; CKD queued for 2027 research work; AFib awaits waveform data</strong></li>
        </ul>
      </Panel>
    </>
  );
}
