import { useMemo, useState } from 'react';
import { Panel, Badge, ProtoTag, StatCard } from '../components/ui/index.js';
import ScatterChart from '../components/charts/ScatterChart.jsx';
import { validationReport } from '../lib/engine.js';

/**
 * Sensor vs Reference Validation Study (module #7).
 * Agreement analysis of the simulated SH-1 device against the simulated
 * reference laboratory: identity plot, Bland-Altman agreement, and a
 * per-biomarker metric table. All pairs are synthetic (n = 40 each) —
 * there is no real device and no real reference laboratory.
 */
export default function ValidationStudy() {
  const [sel, setSel] = useState(validationReport[0].id);

  const v = useMemo(
    () => validationReport.find((r) => r.id === sel) ?? validationReport[0],
    [sel],
  );

  const identityPoints = v.pairs.map((p) => ({ x: p.reference, y: p.device }));
  const baPoints = v.pairs.map((p) => ({
    x: +(((p.device + p.reference) / 2)).toFixed(1),
    y: +(p.device - p.reference).toFixed(2),
  }));

  return (
    <>
      <Panel
        title="Sensor vs reference validation"
        subtitle="Paired device/reference measurements — synthetic pairs, n = 40 per biomarker"
        aside={
          <span className="inline-select">
            <select value={sel} onChange={(e) => setSel(e.target.value)}>
              {validationReport.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.label} ({r.unit})
                </option>
              ))}
            </select>
          </span>
        }
      >
        <div className="stat-grid">
          <StatCard label="Mean bias (device − ref)" value={v.bias} unit={v.unit} note="Positive = device reads high" tone={Math.abs(v.bias) > 3 ? 'warn' : 'good'} />
          <StatCard label="MAE" value={v.mae} unit={v.unit} note="Mean absolute error" />
          <StatCard label="RMSE" value={v.rmse} unit={v.unit} note="Root mean square error" />
          <StatCard label="Pearson r" value={v.r} note="Linear association (synthetic)" tone="info" />
        </div>

        <ScatterChart
          points={identityPoints}
          identity
          height={300}
          xLabel={`Reference laboratory (${v.unit})`}
          yLabel={`Device (${v.unit})`}
        />
        <p className="fact-note" style={{ marginTop: 10 }}>
          Identity plot: dashed line marks perfect agreement (device = reference). Points
          were generated by a seeded pseudo-random generator, not by any instrument.
        </p>
      </Panel>

      <Panel
        title={`Bland-Altman agreement — ${v.label}`}
        subtitle="Difference (device − reference) against the pairwise mean, with 95% limits of agreement"
        aside={<Badge tone="proto">Synthetic pairs</Badge>}
      >
        <ScatterChart
          points={baPoints}
          refLines={[
            { y: v.hiLa, label: `Upper 95% LoA ${v.hiLa}`, tone: 'bad' },
            { y: v.bias, label: `Mean bias ${v.bias}`, tone: 'warn' },
            { y: v.loLa, label: `Lower 95% LoA ${v.loLa}`, tone: 'bad' },
          ]}
          height={300}
          xLabel={`Mean of pair (${v.unit})`}
          yLabel={`Difference (${v.unit})`}
          color="var(--ink-500)"
        />
        <p className="fact-note" style={{ marginTop: 10 }}>
          If the device were unbiased, differences would scatter around zero. The limits of
          agreement are computed as bias ± 1.96 × SD of the differences — on synthetic data,
          so they carry no metrological meaning.
        </p>
      </Panel>

      <Panel
        title="All biomarkers — agreement summary"
        subtitle="Simulated SH-1 multi-biomarker patch vs simulated reference laboratory"
        aside={<ProtoTag compact />}
      >
        <div className="mini-table-wrap">
          <table className="data-table">
            <thead>
              <tr>
                <th>Biomarker</th>
                <th className="num">n</th>
                <th className="num">Bias</th>
                <th className="num">MAE</th>
                <th className="num">RMSE</th>
                <th className="num">r</th>
                <th className="num">95% LoA</th>
              </tr>
            </thead>
            <tbody>
              {validationReport.map((r) => (
                <tr
                  key={r.id}
                  style={r.id === sel ? { background: 'color-mix(in srgb, var(--primary) 6%, var(--surface-1))' } : undefined}
                >
                  <td>
                    {r.label} <span className="fact-note">({r.unit})</span>
                  </td>
                  <td className="num">{r.n}</td>
                  <td className="num">{r.bias}</td>
                  <td className="num">{r.mae}</td>
                  <td className="num">{r.rmse}</td>
                  <td className="num">{r.r}</td>
                  <td className="num">{r.loLa} … {r.hiLa}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <p className="fact-note" style={{ marginTop: 10 }}>
          Every pair in this study is synthetic. The “reference laboratory” is a seeded
          pseudo-random generator in the source code — these numbers must never be quoted
          as device accuracy evidence.
        </p>
      </Panel>
    </>
  );
}
