import { useMemo } from 'react';
import { ecgStripFor } from '../lib/liveVitals.js';

/**
 * EcgStrip — compact ECG trace for a patient card or a report block.
 *
 * The waveform is generated by the bio-signal model in `lib/liveVitals.js` and
 * the rate shown is measured back from the drawn trace. It is decorative demo
 * output: it visualises the profile's simulated resting rate, it is not a
 * recording and it is never used as a clinical finding.
 */
export default function EcgStrip({
  profile,
  atMs,
  bpm = null,
  seconds = 6,
  height = 56,
  showRate = true,
  tone = 'good',
  label,
}) {
  const strip = useMemo(
    () => ecgStripFor(profile, { atMs, seconds, points: 240, bpm }),
    [profile?.id, atMs, seconds, bpm],
  );

  const points = strip.points;
  const w = 240;
  const h = 100;
  const path = points
    .map((v, i) => {
      const x = (i / (points.length - 1)) * w;
      const y = h / 2 - v * (h * 0.36);
      return `${i === 0 ? 'M' : 'L'}${x.toFixed(2)},${y.toFixed(2)}`;
    })
    .join(' ');

  return (
    <div className={`ecg-strip tone-${tone}`} style={{ '--ecg-height': `${height}px` }}>
      <svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" role="img" aria-label={label ?? `ECG strip for ${profile?.name ?? 'profile'}`}>
        <defs>
          <pattern id="ecg-grid-pattern" width="10" height="10" patternUnits="userSpaceOnUse">
            <path d="M10 0 L0 0 0 10" fill="none" stroke="currentColor" strokeOpacity="0.16" strokeWidth="0.5" />
          </pattern>
        </defs>
        <rect x="0" y="0" width={w} height={h} fill="url(#ecg-grid-pattern)" />
        <line x1="0" y1={h / 2} x2={w} y2={h / 2} stroke="currentColor" strokeOpacity="0.22" strokeWidth="0.6" />
        <path d={path} fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round" />
      </svg>
      {showRate && (
        <div className="ecg-strip-meta">
          <span className="ecg-rate">
            {strip.bpm != null ? `${strip.bpm} bpm` : 'rate not measurable'}
          </span>
          <span className="ecg-strip-note">
            {strip.peaks} QRS in {seconds}s · synthesised demo waveform
            {strip.bpm != null ? ' · rate measured from the trace' : ''}
          </span>
        </div>
      )}
    </div>
  );
}
